- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "target/2023mavenWebAppPipelineWithAnsible.war"
        dest: "/opt/tomcat/webapps/2023mavenWebAppPipelineWithAnsible.war"

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh || true
        /opt/tomcat/bin/startup.sh
